# Generated by Django 3.0.8 on 2020-07-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30)),
                ('decr', models.CharField(max_length=300)),
                ('date', models.DateField()),
            ],
        ),
    ]
